SELECT APELLIDO, OFICIO, DEPT_NO FROM EMPLEADOS;

SELECT DEPT_NO, DNOMBRE, LOC FROM DEPARTAMENTOS;

SELECT * FROM EMPLEADOS;

SELECT * FROM EMPLEADOS ORDER BY APELLIDO;

SELECT * FROM EMPLEADOS ORDER BY DEPT_NO DESC;

SELECT * FROM EMPLEADOS ORDER BY DEPT_NO DESC, APELLIDO DESC;

SELECT * FROM EMPLEADOS WHERE SALARIO>2000;

SELECT * FROM EMPLEADOS WHERE OFICIO='ANALISTA';

SELECT APELLIDO, OFICIO FROM EMPLEADO WHERE DEPT_NO=20;

SELECT * FROM EMPLEADOS WHERE OFICIO='VENDEDOR' ORDER BY APELLIDO;

SELECT * FROM EMPLEADOS WHERE DEPT_NO=10 AND OFICIO='ANALISTA' ORDER BY APELLIDO;

SELECT * FROM EMPLEADOS WHERE DEPT_NO=20 AND SALARIO>2000;

SELECT * FROM EMPLEADOS ORDER BY OFICIO, APELLIDO;

SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'A%';

SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE '%Z';

SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'A%' AND OFICIO LIKE '%E%';

SELECT * FROM EMPLEADOS WHERE SALARIO BETWEEN 1000 AND 1700;

SELECT * FROM EMPLEADOS WHERE OFICIO='VENDEDOR' AND COMISION>600;

SELECT * FROM EMPLEADOS ORDER BY DEPT_NO, APELLIDO;

SELECT EMP_NO, APELLIDO FROM EMPLEADOS WHERE APELLIDO LIKE '%Z' AND SALARIO>2000;

SELECT * FROM DEPARTAMENTOS WHERE LOC LIKE 'B%';

SELECT * FROM EMPLEADOS WHERE OFICIO='EMPLEADO' AND SALARIO>200 AND DEPT_NO=10;

SELECT * FROM EMPLEADOS WHERE COMISION=0 OR COMISION IS NULL;

SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'J%' AND (COMISION=0 OR COMISION IS NULL);

SELECT APELLIDO FROM EMPLEADOS WHERE OFICIO='VENDEDOR' OR OFICIO='ANALISTA' OR OFICIO='EMPLEADO';

SELECT APELLIDO FROM EMPLEADOS WHERE OFICIO NOT IN('ANALISTA','EMPLEADO') AND SALARIO>2000;

SELECT * FROM EMPLEADOS WHERE SALARIO BETWEEN 2000 AND 3000;

SELECT APELLIDO,SALARIO,DEPT_NO FROM EMPLEADOS WHERE SALARIO>2000 AND DEPT_NO IN(10,30);

SELECT APELLIDO, EMP_NO FROM EMPLEADOS WHERE SALARIO NOT BETWEEN 1000 AND 2000;

SELECT LOWER(APELLIDO) FROM EMPLEADOS;

SELECT CONCAT(APELLIDO,' ',OFICIO) FROM EMPLEADOS;

SELECT APELLIDO, LENGTH(APELLIDO) AS LONGITUD FROM EMPLEADOS ORDER BY LONGITUD DESC;

SELECT EMP_NO,APELLIDO,YEAR(FECHA_ALT) AS AÑO_CONTRATACION FROM EMPLEADOS;

SELECT EMP_NO,APELLIDO,YEAR(FECHA_ALT) AS AÑO_CONTRATACION FROM EMPLEADOS WHERE YEAR(FECHA_ALT)=1992;

SELECT EMP_NO,APELLIDO,MONTHNAME(FECHA_ALT) AS MES_CONTRATACION FROM EMPLEADOS WHERE MONTHNAME(FECHA_ALT)='FEBRUARY';

SELECT APELLIDO, GREATEST(SALARIO, IFNULL(COMISION,0)) AS MAYOR_VALOR FROM EMPLEADOS;

SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'A%' AND YEAR(FECHA_ALT)=1990;

SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'A%' AND YEAR(FECHA_ALT)=1990;







