CREATE TABLE PROYECTO(
    NOMBRE VARCHAR(25) PRIMARY KEY,
    FECHA_INICIO DATE
);

CREATE TABLE PROYECTOREVISION(
    NOMBRE_PROYECTO VARCHAR(25) PRIMARY KEY,
    MOTIVOREVISION VARCHAR(250),
    CONSTRAINT FK_PROYECTOREVISION FOREIGN KEY(NOMBRE_PROYECTO)
    REFERENCES PROYECTO(NOMBRE)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE PROYECTONUEVO(
    NOMBRE_PROYECTO VARCHAR(25) PRIMARY KEY,
    PRESUPUESTO INT(20),
    CONSTRAINT FK_PROYECTONUEVO FOREIGN KEY(NOMBRE_PROYECTO)
    REFERENCES PROYECTO(NOMBRE)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE INVESTIGADOR(
    DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(50),
    LOCALIDAD VARCHAR(50),
    TELEFONO CHAR(9),
    NOMBRE_PROYECTO VARCHAR(25),
    CONSTRAINT FK_PROYECTO FOREIGN KEY(NOMBRE_PROYECTO)
    REFERENCES PROYECTO(NOMBRE)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE JEFEINVESTIGADOR(
    DNI_INVESTIGADOR VARCHAR(9) PRIMARY KEY,
    DNI_JEFE VARCHAR(9),
    CONSTRAINT FK_DNI_INVESTIGADOR FOREIGN KEY(DNI_INVESTIGADOR)
    REFERENCES INVESTIGADOR(DNI)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_DNI_JEFE FOREIGN KEY(DNI_JEFE)
    REFERENCES INVESTIGADOR(DNI)
    ON UPDATE CASCADE
    ON DELETE RESTRICT    
);

CREATE TABLE CONFERENCIA(
    NOMBRE VARCHAR(25),
    FECHA DATE,
    NORAINICIO TIME,
    NUMHORAS INT(4),
    LUGAR VARCHAR(40),
    CONSTRAINT PK_CONFERENCIA PRIMARY KEY(NOMBRE, FECHA)
);

CREATE TABLE INVESTIGADORCONFERENCIA(
    NOMBRE_CONFERENCIA VARCHAR(25),
    DNI_INVESTIGADOR VARCHAR(9),
    CONSTRAINT PK_INVESTIGADORCONFERENCIA PRIMARY KEY(NOMBRE_CONFERENCIA, DNI_INVESTIGADOR),
    CONSTRAINT FK_CONFERENCIA FOREIGN KEY(NOMBRE_CONFERENCIA)
    REFERENCES CONFERENCIA(NOMBRE)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT FK_DNI_INVERTIGADOR FOREIGN KEY(DNI_INVESTIGADOR)
    REFERENCES INVESTIGADOR(DNI)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);