CREATE TABLE CLIENTE(
    IDCLIENTE INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    TIPO BOOLEAN
);

CREATE TABLE CLIENTECREDITO(
    IDCLIENTE INT(9) PRIMARY KEY,
    CUENTA_BANCARIA VARCHAR(24),
    FECHAPAGO DATE,
    CONSTRAINT FK_CLIENTE FOREIGN KEY(IDCLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE MEDICAMENTO(
    IDMEDICAMENTO INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    TIPO VARCHAR(25),
    UNIDADESSTOCK INT(9),
    UNIDADESVENDIDAS INT(9),
    PRECIO INT(9)
);

CREATE TABLE LABORATORIO(
    IDLABORATORIO INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    TELEFONO VARCHAR(9),
    DIRECCION VARCHAR(30),
    FAX VARCHAR(30),
    PERSONACONTACTO VARCHAR(30)
);

CREATE TABLE VENTA(
    IDMEDICAMENTO INT(9),
    IDCLIENTE INT(9),
    FECHACOMPRA DATE,
    UNIDADES INT(9),
    CONSTRAINT PK_VENTA PRIMARY KEY(IDMEDICAMENTO, IDCLIENTE, FECHACOMPRA),
    CONSTRAINT FK_MEDICAMENTO_VENTA FOREIGN KEY(IDMEDICAMENTO)
    REFERENCES MEDICAMENTO(IDMEDICAMENTO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_CLIENTE_VENTA FOREIGN KEY(IDCLIENTE)
    REFERENCES CLIENTECREDITO(IDCLIENTE)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE COMPRA(
    IDLABORATORIO INT(9),
    IDMEDICAMENTO INT(9),
    CONSTRAINT PK_COMPRA PRIMARY KEY(IDMEDICAMENTO, IDLABORATORIO),
    CONSTRAINT FK_LABORATORIO_COMPRA FOREIGN KEY(IDLABORATORIO)
    REFERENCES LABORATORIO(IDLABORATORIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_MEDICAMENTO_COMPRA FOREIGN KEY(IDMEDICAMENTO)
    REFERENCES MEDICAMENTO(IDMEDICAMENTO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);