CREATE TABLE POLIZA(
    CODPOLIZA INT(9) PRIMARY KEY,
    DATOS VARCHAR(250)
);

CREATE TABLE ASEGURADO(
    CODPOLIZA INT(9) PRIMARY KEY,
    NUM_CORRELATIVO INT(9),
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(40),
    CATEGORIA VARCHAR(15),
    CONSTRAINT FK_CODPOLIZA FOREIGN KEY(CODPOLIZA)
    REFERENCES POLIZA(CODPOLIZA)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE HOSPITAL(
    CODHOSPITAL INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(25),
    NUM_CAMAS INT(9)
);

CREATE TABLE AREA(
    CODAREA INT(9) PRIMARY KEY,
    NUM_HABITANTES INT(9),
    SUPERFICIE INT(9)
);

CREATE TABLE HOSPITALCONCERTADO(
    CODHOSPITAL INT(9) PRIMARY KEY,
    CODAREA INT(9),
    SERVICIOS VARCHAR(50),
    PRESUPUESTO INT(9),
    NOMBRE VARCHAR(30),
    NUM_CAMAS INT(9),
    CONSTRAINT FK_HOSPITAL FOREIGN KEY(CODHOSPITAL)
    REFERENCES HOSPITAL(CODHOSPITAL)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_AREA_HOSPITAL FOREIGN KEY(CODAREA)
    REFERENCES AREA(CODAREA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE MEDICO(
    CODMEDICO INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    TELEFONO VARCHAR(9),
    CODAREA INT(9),
    CONSTRAINT FK_AREA_MEDICO FOREIGN KEY(CODAREA)
    REFERENCES AREA(CODAREA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE JEFEMEDICO(
    CODMEDICOJEFE INT(9),
    CODMEDICO INT(9) PRIMARY KEY,
    CONSTRAINT FK_JEFE_MEDICO FOREIGN KEY(CODMEDICOJEFE)
    REFERENCES MEDICO(CODMEDICO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT FK_MEDICO FOREIGN KEY(CODMEDICO)
    REFERENCES MEDICO(CODMEDICO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE HOSPITALIZACION(
    CODPOLIZA INT(9),
    CODHOSPITAL INT(9),
    FECHAINICIO DATE,
    CODMEDICO INT(9),
    FECHAFIN DATE,
    CONSTRAINT PK_HOSPITALIZACION PRIMARY KEY(CODPOLIZA, CODHOSPITAL,FECHAINICIO),
    CONSTRAINT FK_CODPOLIZA_HOSPITALIZACION FOREIGN KEY(CODPOLIZA)
    REFERENCES ASEGURADO(CODPOLIZA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_CODHOSPITAL_HOSPITALIZACION FOREIGN KEY(CODHOSPITAL)
    REFERENCES HOSPITAL(CODHOSPITAL)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_CODMEDICO_HOSPITALIZACION FOREIGN KEY(CODMEDICO)
    REFERENCES MEDICO(CODMEDICO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);