CREATE TABLE SOCIO(
    NUM_SOCIO INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    DIRECCION VARCHAR(40),
    TELEFONO VARCHAR(9),
    NUM_SOCIO_AVAL INT(9),
    TIENEPROBLEMAS BOOLEAN,
    CONSTRAINT FK_AVAL FOREIGN KEY (NUM_SOCIO_AVAL)
    REFERENCES SOCIO(NUM_SOCIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE PRODUCTORA(
    NOMBRE VARCHAR(25) PRIMARY KEY,
    NACIONALIDAD VARCHAR(25)
);

CREATE TABLE DIRECTOR(
    ID_DIRECTOR INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    NACIONALIDAD VARCHAR(30)
);

CREATE TABLE PELICULA(
    TITULO VARCHAR(30),
    FECHA DATE,
    PRODUCTORA VARCHAR(25),
    ID_DIRECTOR INT(9),
    CONSTRAINT PK_PELICULA PRIMARY KEY (TITULO, FECHA),
    CONSTRAINT FK_PRODUCTORA FOREIGN KEY (PRODUCTORA)
    REFERENCES PRODUCTORA(NOMBRE)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_DIRECTOR FOREIGN KEY (ID_DIRECTOR)
    REFERENCES DIRECTOR(ID_DIRECTOR)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE ACTOR(
    ID_ACTOR INT(9) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    NACIONALIDAD VARCHAR(30),
    SEXO VARCHAR(30)
);

CREATE TABLE PELICULAREPARTO(
    TITULO VARCHAR(30),
    ID_ACTOR INT(9),
    CONSTRAINT PK_REPARTO PRIMARY KEY (TITULO, ID_ACTOR),
    CONSTRAINT FK_REPARTO_TITULO FOREIGN KEY (TITULO)
    REFERENCES PELICULA(TITULO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT FK_REPARTO_ACTOR FOREIGN KEY (ID_ACTOR)
    REFERENCES ACTOR(ID_ACTOR)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE EJEMPLAR(
    NUM_EJEMPLAR INT(9),
    TITULO VARCHAR(30),
    ESTADO VARCHAR(20),
    ALQUILADO BOOLEAN,
    CONSTRAINT PK_EJEMPLAR PRIMARY KEY (NUM_EJEMPLAR, TITULO),
    CONSTRAINT FK_EJEMPLAR_TITULO FOREIGN KEY (TITULO)
    REFERENCES PELICULA(TITULO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE ALQUILER(
    TITULO VARCHAR(30),
    NUM_EJEMPLAR INT(9),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_SOCIO INT(9),
    CONSTRAINT PK_ALQUILER PRIMARY KEY (TITULO, NUM_EJEMPLAR, FECHA_INICIO, NUM_SOCIO),
    CONSTRAINT FK_TITULO_ALQUILER FOREIGN KEY (TITULO)
    REFERENCES PELICULA(TITULO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_EJEMPLAR_ALQUILER FOREIGN KEY (NUM_EJEMPLAR)
    REFERENCES EJEMPLAR(NUM_EJEMPLAR)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT FK_NUM_SOCIO_EJEMPLAR FOREIGN KEY (NUM_SOCIO)
    REFERENCES SOCIO(NUM_SOCIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);